### ISSUE TITLE
Suporte Oficial do ReceitaWS

### ISSUE THREAD

**Issue by vkruoso** [rafaelcaviquioli/receita-ws#3]
Olá @rafaelcaviquioli . Sou o @vkruoso, criador e mantenedor do site ReceitaWS.

Gostei bastante do seu plugin. O que acha de mover este repo para uma organização? Gostaria de ter bibliotecas como estas em várias linguagens. Tenho um repositório de uma biblioteca em Python ([@vkruoso/receita-tools](https://github.com/vkruoso/receita-tools)) que estaria junto com este.

**Comment by rafaelcaviquioli** [comment]
Olá @vkruoso, com certeza estou disposto a fazer isso.
E como podemos fazer isso?

**Comment by rafaelcaviquioli** [comment]
Olá @vkruoso, como podemos fazer isso?

**Comment by vkruoso** [comment]
Minha sugestão seria criarmos uma organização ``receitaws`` e dentro dela migrar o receita-tools (com este nome ou apenas ``tools``, e este repo com o nome de ``jquery-plugin``? O que acha?
